<div class="mb-3" style=" margin-top: 100px; ">
	<div class="row row-cols-auto g-3">
		<div class="w-100 text-center">
			<span class="d-block fs-1"><i class="fadeIn animated bx bx-lock-alt"></i></span>
			<span class="w-100 fs-5 text-black d-block mb-1">Hmmm... We're sorry.</span>
			<span class="w-100 fs-6 text-black d-block"><b>You don't have permission</b> to view this page.</span>
			
			<span class="contact-administrator">Please contact your administrator.</span>
			<style>
			.contact-administrator {
				background: #f4f4f7;
				border-left: 2px solid #5989d6;
				padding: 5px 12px;
				display: block;
				width: 290px;
				text-align: center;
				margin: auto;
				margin-top: 15px;
				color: #707070;
			}
			</style>
		</div>
	</div>
</div>
